// Test-only entry point. The published extension entry is src/index.ts.
export { default } from "./extension.js";
import {
  expandBlock,
  isSyntheticRef,
  parseMsgIds,
  readCapped,
  readSessionMessages,
  renderMessage,
  splitMessageId,
} from "./expand.js";
import {
  MemoryDb,
  loadSqlite,
  scanSources,
  scanAll,
  scanCurrentSession,
  piSessionCwdMap,
  piSessionHeaderCwd,
  loadOpencodeSessionMap,
  listSourceFiles,
  loadSources,
  getDb,
  formatResults,
  redactSecrets,
  sanitizeCfg,
  collectMsgIds,
  configureForTests,
  resetPiHeaderReadCount,
  getPiHeaderReadCount,
} from "./extension.js";

export { expandBlock, isSyntheticRef, parseMsgIds, readCapped, readSessionMessages, renderMessage, splitMessageId };

export const internals = {
  MemoryDb,
  loadSqlite,
  scanSources,
  scanAll,
  scanCurrentSession,
  piSessionCwdMap,
  piSessionHeaderCwd,
  loadOpencodeSessionMap,
  listSourceFiles,
  loadSources,
  getDb,
  formatResults,
  redactSecrets,
  sanitizeCfg,
  collectMsgIds,
  _setConfig: configureForTests,
  _resetPiHeaderReadCount: resetPiHeaderReadCount,
  _piHeaderReadCount: getPiHeaderReadCount,
  expandBlock,
  isSyntheticRef,
  parseMsgIds,
  readCapped,
  readSessionMessages,
  renderMessage,
  splitMessageId,
};
